name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'  # or your desired Go version

      # Cache Go modules for faster builds (optional but recommended)
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Build the application
      - name: Build
        run: go build ./...
