name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'  # or your desired Go version

      # Cache Go modules for faster builds (optional but recommended)
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Build the application
      - name: Build
        run: go build ./...

      # Determine the next version based on conventional commits
      - name: Determine Next Version
        id: determine_version
        uses: paulhatch/semantic-version@v3
        with:
          branch: main    

      # Determine the next version and tag the commit
      - name: Tag and Release
        id: tag_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.determine_version.outputs.new_version }}
          release_name: Release ${{ steps.determine_version.outputs.new_version }}
          draft: false
          prerelease: false

