name: Publish TS

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/publish-ts-lib.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'scripts/**'
      - '.github/workflows/publish-ts-lib.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Needed for JSR authentication

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Publish to JSR
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: cd scripts/lib && deno publish
        