name: Go Smoke Test

on:
  release:
    types: [created]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from your repository
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Set up the Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'  # or your desired Go version

      # Cache Go modules for faster builds (optional but recommended)
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Build the application
      - name: Install
        run: go install github.com/wcatron/query-projects@${{ github.event.release.tag_name }}

      - name: Run
        run: |
            export PATH="${PATH}:$(go env GOPATH)/bin"
            query-projects info
